###########
# site.title

title:    'NullCraft'
subtitle: 'NullCraft: An agent who know how to choose the reward path -- Less Is More'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
