###########
# site.title

title:    'NullCraft'
subtitle: 'NullCraft: An agent who wants to collect all the continous carrots'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
