###########
# site.title

title:    'NullCraft'
subtitle: 'NullCraft: An agent who wants to collect all the carrot and left 'null' of the carrot'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
